# SPDX-FileCopyrightText: Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
#
# SPDX-License-Identifier: MIT
#
# golangci-lint configuration for OpenCHAMI ex-bootstrap
# Documentation: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
  # Note: exclusions.paths suppresses issues but doesn't skip analysis.
  # The pre-commit hook temporarily renames the examples directory to
  # completely skip it, which is more performant and avoids import errors.
  exclusions:
    paths:
      - examples/
      - test/integration/

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
